CREATE TABLE IF NOT EXISTS guilds
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    guild_id   VARCHAR(32)  NOT NULL UNIQUE,
    guild_name VARCHAR(512) NOT NULL,
    owner_id   VARCHAR(32)  NOT NULL,
    version    INTEGER      NOT NULL DEFAULT 1,
    ctime      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);