CREATE TABLE IF NOT EXISTS guilds
(
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    name      VARCHAR(512) UNIQUE         NOT NULL,
    version   INTEGER                     NOT NULL DEFAULT 1,
    ctime     TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime     TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);